### PR TITLE
now google guava is shaded

### PR DESCRIPTION
**Pull request by treblereel**
it isn't necessary to add crysknife annotation to the deps
little error logging fix

### CODE REVIEW

**Comment by hrstoyanov** [comment]
@treblereel are you removing guava?  At the time, I removed a lot of dependencies from Errai, but could not get rid of Guava, because some Guava classes already leaked into the public Errai API (like pages). If you have the opportunity and want to tweak the Errai public APIs, please remove guava - there are ways to acheve the same with modern Java.

**Comment by treblereel** [comment]
@hrstoyanov nope, i have some issues using guava, so i did a working port of it. 
here https://github.com/treblereel/crysknife/tree/master/ui/databinding/api/src/main/java/com/google/common

**Comment by treblereel** [comment]
@hrstoyanov Yeap, you are right, i ll do that, i need guava mostly because some ported code still uses some guava collections like Multimap and so on, i think it's better to rewrite it coz it adds ~140kb to the project which use it, without any profit.

**Comment by hrstoyanov** [comment]
Exactly! And this Multimaps in the public pages API can be re-done with something standard, because crysknife is separate project and breaking changes are ok.

**Pull request merged**
